#!/usr/bin/env node
var exec = require('child_process').exec
  , spawn = require('child_process').spawn
  , format = require('util').format
  , fs = require('fs');

var opt = require('optimist'),
    argv = opt
    .options('help', {})
    .argv;

var HELP = ['usage: package [action]'
          , ''
          , 'Builds a mongo shell release.'
          , ''
          , 'actions:'
          , '  all      <node-version>                 Build a release against specified node version, ex: package build v1.8.17'
          , '  bundle   <node-version>                 Build a new mongo.js bundle and compile the mongo shell'
          , ''
          , 'options:'
          , '  --help                                  Show help.'
          , ''].join('\n');


  // case 'bundle': bundle(); break;
  // case 'compile': compile(); break;
  // case 'clean': compile(); break;  
  // case 'download': compile(); break;  

function buildBundle(version, options, callback) {
  var file_name = format("output/node-%s/lib/mongo.js", version);
  var build_command = format("./tools/one/bin/onejs build package.json output/node-%s/lib/mongo.js", version);
  var third_party_file = format("output/node-%s/lib/_third_party_main.js", version);
  var copy_command = format("cp ext/node_sync.* output/node-%s/src", version);
  var node_gyp = format("output/node-%s/node.gyp", version);
  var node_file = format("output/node-%s/src/node.cc", version);
  var node_extensions = format("output/node-%s/src/node_extensions.h", version);

  if(typeof options == 'function') {
    callback = options;
    options = {};
  }

  exec(build_command, {}, function(error, stdout, stderr) {
    console.log(stdout)
    console.log(stderr)

    // Apply change to file for the sync library
    var file = fs.readFileSync(file_name, 'utf8');
    file = file.replace("require('../build/Release/sync')", "process.binding('sync')");
    fs.writeFileSync(file_name, file, 'utf8');

    if(options.js_only) return callback();

    // Create the _third_party_main.js file
    fs.writeFileSync(third_party_file, "require('mongo');", 'utf8');

    // Copy the c++ files over to the correct directory
    exec(copy_command, {}, function(error, stdout, stderr) {
      console.log(stdout)
      console.log(stderr)

      //
      // node.gyp
      // Modify the node.gyp file
      var node_gyp_data = fs.readFileSync(node_gyp, 'utf8');
      // Add the files to the gyp file
      node_gyp_data = node_gyp_data.replace("'library_files': [", "'library_files': ['lib/mongo.js','lib/_third_party_main.js',");
      node_gyp_data = node_gyp_data.replace("'sources': [", "'sources': ['src/node_sync.h', 'src/node_sync.cc',");
      // Write file back
      fs.writeFileSync(node_gyp, node_gyp_data, 'utf8');

      //
      // node.cc
      // Modify the node.cc file
      var node_cc = fs.readFileSync(node_file, 'utf8');
      // Add the node_sync header
      node_cc = node_cc.replace('#include "node.h"', "#include \"node.h\"\n#include \"node_sync.h\"");
      // Write file back
      fs.writeFileSync(node_file, node_cc, 'utf8');

      //
      // node_extensions.h
      // Modify the node_extensions.h file
      var node_extensions_data = fs.readFileSync(node_extensions, 'utf8');
      // Add the module
      node_extensions_data = node_extensions_data.replace("NODE_EXT_LIST_ITEM(node_fs_event_wrap)", "NODE_EXT_LIST_ITEM(node_fs_event_wrap)\nNODE_EXT_LIST_ITEM(node_sync)");
      // Write file back
      fs.writeFileSync(node_extensions, node_extensions_data, 'utf8');

      // Done
      callback(null);
    })
  });
}

function compileNode(version, callback) {
  var final_file = format("cp output/node-%s/out/Release/node* ./build/mongo", version);
  var dir = format("output/node-%s", version)

  var make = spawn('make', ['-C', dir]);
  make.stdout.on('data', function(data) {
    console.log(data.toString());
  })

  make.stderr.on('data', function (data) {
    console.log(data.toString());
  });

  make.on('exit', function() {
    // Copy final binary to build directory
    exec(final_file, {}, function(error, stdout, stderr) {
      console.log(stdout)
      console.log(stderr)

      callback(null);
    })
  });
}

function createBuildDirectory(callback) {
  exec('rm -rf output', {}, function(error, stdout, stderr) {
    exec('mkdir output', {}, function(error, stdout, stderr) {
      console.log(stdout)
      console.log(stderr)
      callback(null);
    });  
  });  
}

function checkoutNodeSource(version, callback) {
  var node_file = format("http://nodejs.org/dist/%s/node-%s.tar.gz", version, version);
  var curl_command = format("curl %s -o output/node-%s.tar.gz", node_file, version);
  var tar_comand = format("cd output; tar xvfz node-%s.tar.gz", version);
  console.log(curl_command)

  // Fetch node.js
  exec(curl_command, {}, function(error, stdout, stderr) {
    console.log(stdout)
    console.log(stderr)

    // Unpack the node js version
    exec(tar_comand, {}, function(error, stdout, stderr) {
      console.log(stdout)
      console.log(stderr)
      callback(null);
    });
  });  
}

function help(){
  console.log(HELP);
  process.exit(0);
}

function all() {
  var version = argv._[1] || 'v0.8.19';

  createBuildDirectory(function() {  
    checkoutNodeSource(version, function() {
      buildBundle(version, function() {
        compileNode(version, function() {        
        });
      })
    })
  })
}

/**
 * Only builds the mongo.js file again and the recompiles the mongo
 */
function bundle() {
  var version = argv._[1] || 'v0.8.19';  
  buildBundle(version, {js_only:true}, function() {
    compileNode(version, function() {
    });
  });
}

var action = argv._[0];

switch(action){
  case 'all': all(); break;
  case 'bundle': bundle(); break;
  default:
    if(argv.version){
      version();
    } else {
      help();
    }
}